### PR TITLE
enhance read-until and read-until-or,  support connect timeout and default timeout options for get-telnet

### PR DESCRIPTION
**Pull request by cdzwm**
Suport Regex and String in patterns of read-until and read-until-or. Support connection timeout and default timeout for get-telnet.

### CODE REVIEW

**Comment by komcrad** [comment]
Thanks for addressing the comments and for your contribution.

**Comment by komcrad** [comment]
What's up with the author name of the last two commits?
```
commit 5432670afd955ffd5d6193713dc5524514da1c91 (HEAD -> master, origin/master, origin/HEAD)
Author: canw <a@a.com>
Date:   Wed May 15 11:30:16 2019 +0800

    Add some tests

```

**Comment by cdzwm** [comment]
my git config issue. 
How can i correct it?




------------------ 原始邮件 ------------------
发件人: "komcrad"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 中午11:57
收件人: "komcrad/clj-telnet"<clj-telnet@noreply.github.com>;
抄送: "canw学无止境"<495720919@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [komcrad/clj-telnet] enhance read-until and read-until-or, support connect timeout and default timeout options for get-telnet (#11)




What's up with the author name of the last two commits?
 commit 5432670afd955ffd5d6193713dc5524514da1c91 (HEAD -> master, origin/master, origin/HEAD) Author: canw <a@a.com> Date:   Wed May 15 11:30:16 2019 +0800     Add some tests

**Comment by komcrad** [comment]
I've used this before:
https://help.github.com/en/articles/changing-author-info

But for future reference you probably want to
`git config --global user.email "email@example.com"`
and
`git config --global user.name "example.name"`

**Pull request closed without merging**
